export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SORT_TYPE = 'SORT_TYPE';
export const FILTER_TYPE = 'FILTER_TYPE';
export const PAGE_NUM ='PAGE_NUM';
export const PAGE_RESET ='PAGE_RESET';
export const SEARCH_FIELD = 'SEARCH_FIELD';
export const Cookies='Cookies'